repos:
  - repo: local
    hooks:
      - id: client-lint
        name: Lint client
        entry: bash -c 'cd client && yarn lint' _
        language: system
        files: '^client/.*\.(ts|tsx)$'

      - id: server-lint
        name: Lint server
        entry: bash -c 'cd server && bun lint' _
        language: system
        files: '^server/.*\.(ts|js)$'

      - id: cli-lint
        name: Lint CLI
        entry: bash -c 'cd cli && cargo clippy -- -D warnings'
        language: system
        files: '^cli/.*\.rs$'
        pass_filenames: false
